- name: Cancel instances
  hosts: localhost
  gather_facts: False
  tasks:
  - name: Destroying servers...
    sl_vm:
      state: absent
      hostname: "{{ item }}"
    with_lines: cat "./hosts_to_create.txt"
